from launchers.GameLauncher import GameLauncher

# Do not edit this file to start a game with different settings.
# This is a templated that should be copied to ignoredMainGameLauncher.py.
gameLauncher = GameLauncher(True)
gameLauncher.runServerBackground()
gameLauncher.runJavaAiBackground("clientAis.implementations.basic_minion_wielder.BasicMinionWielder")
gameLauncher.runPythonAiBackground("shortMachine")
gameLauncher.runCppClientGuiBlocking(mode="player")